### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by okumo** [puigalex/deteccion-objetos-video#14]
Cuando quiero hacer el entrenamiento para un logo, esto quiere decir una sola clase. Me sale el siguiente error al ejecutar el entrenamiento:
`Traceback (most recent call last):`
  `File "train.py", line 56, in <module>`
  `  model = Darknet(opt.model_def).to(device)`
 ` File "/home/oscar/Documentos/Proyectos/deteccion-objetos-video/models.py", line 256, in _init_`
    `self.hyperparams, self.module_list = create_modules(self.module_defs)`
 ` File "/home/oscar/Documentos/Proyectos/deteccion-objetos-video/models.py", line 79, in create_modules`
  `  num_classes = int(module_def["classes"])`
`ValueError: invalid literal for int() with base 10: ''`

**Comment by okumo** [comment]
Ya lo solucioné, tuve que eliminar el archivo yolov3-custom.cfg y volver a ejecutar el comando para crear ese archivo.
